<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\ShopStock.Application\ShopStock.Application.csproj" />
    <ProjectReference Include="..\ShopStock.Domain\ShopStock.Domain.csproj" />
    <ProjectReference Include="..\ShopStock.Infra.Data\ShopStock.Infra.Data.csproj" />
  </ItemGroup>

</Project>
